version = 5.3.1
archive_dir = /etc/letsencrypt/archive/npm-35
cert = /etc/letsencrypt/live/npm-35/cert.pem
privkey = /etc/letsencrypt/live/npm-35/privkey.pem
chain = /etc/letsencrypt/live/npm-35/chain.pem
fullchain = /etc/letsencrypt/live/npm-35/fullchain.pem
[renewalparams]
account = cd3665f975e29569aab21f93240ec048
key_type = ecdsa
elliptic_curve = secp384r1
preferred_chain = ISRG Root X1
pref_challs = http-01,
config_dir = /etc/letsencrypt
work_dir = /tmp/letsencrypt-lib
logs_dir = /data/logs
authenticator = webroot
webroot_path = /data/letsencrypt-acme-challenge,
server = https://acme-v02.api.letsencrypt.org/directory
[[webroot_map]]
2501115.rai.cortie.io = /data/letsencrypt-acme-challenge
2501115.robotandi.deamon.io = /data/letsencrypt-acme-challenge
