#!/usr/bin/env python3
import argparse
import os
import smtplib
import ssl
import sys
import tarfile
from datetime import datetime
from email.message import EmailMessage
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Archive student folders and email the archive via SMTP."
    )
    parser.add_argument(
        "--students-root",
        default="/home/rai/deamon/Omni/students",
        help="Root directory that contains student folders.",
    )
    parser.add_argument(
        "--work-dir",
        default="/home/rai/deamon/Omni/.artifacts",
        help="Directory used to write generated archives.",
    )
    parser.add_argument(
        "--to",
        default=os.getenv("MAIL_TO", "robotandi@naver.com"),
        help="Destination email address.",
    )
    parser.add_argument(
        "--subject-prefix",
        default="[Omni] Student folders archive",
        help="Email subject prefix.",
    )
    parser.add_argument(
        "--keep-days",
        type=int,
        default=7,
        help="How many days of archives to keep in work-dir.",
    )
    return parser.parse_args()


def get_student_dirs(students_root: Path) -> list[Path]:
    if not students_root.exists():
        raise FileNotFoundError(f"Students root not found: {students_root}")

    student_dirs: list[Path] = []
    for p in sorted(students_root.iterdir()):
        if not p.is_dir():
            continue
        if not p.name.isdigit():
            continue
        if p.name == "0000000":
            continue
        student_dirs.append(p)

    if not student_dirs:
        raise RuntimeError("No student directories were found to archive.")

    return student_dirs


def build_archive(student_dirs: list[Path], students_root: Path, work_dir: Path) -> Path:
    now = datetime.now()
    stamp = now.strftime("%Y%m%d_%H%M%S")
    archive_path = work_dir / f"students_archive_{stamp}.tar.gz"

    work_dir.mkdir(parents=True, exist_ok=True)

    with tarfile.open(archive_path, mode="w:gz") as tf:
        for d in student_dirs:
            tf.add(d, arcname=str(Path("students") / d.name), recursive=True)

    return archive_path


def cleanup_old_archives(work_dir: Path, keep_days: int) -> None:
    if keep_days < 1:
        return

    cutoff = datetime.now().timestamp() - (keep_days * 86400)
    for p in work_dir.glob("students_archive_*.tar.gz"):
        try:
            if p.stat().st_mtime < cutoff:
                p.unlink(missing_ok=True)
        except OSError:
            continue


def read_mail_env() -> dict[str, str]:
    required = ["SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASS"]
    env: dict[str, str] = {}
    missing: list[str] = []

    for k in required:
        v = os.getenv(k, "").strip()
        if not v:
            missing.append(k)
        else:
            env[k] = v

    if missing:
        raise RuntimeError(
            "Missing mail environment variables: " + ", ".join(missing)
        )

    env["MAIL_FROM"] = os.getenv("MAIL_FROM", env["SMTP_USER"]).strip()
    return env


def send_mail(archive_path: Path, recipient: str, subject_prefix: str) -> None:
    mail_env = read_mail_env()

    msg = EmailMessage()
    msg["From"] = mail_env["MAIL_FROM"]
    msg["To"] = recipient
    msg["Subject"] = f"{subject_prefix} - {archive_path.name}"
    msg.set_content(
        "Attached is the automatic archive of student folders generated by the 04:10 job."
    )

    with open(archive_path, "rb") as f:
        data = f.read()

    msg.add_attachment(
        data,
        maintype="application",
        subtype="gzip",
        filename=archive_path.name,
    )

    smtp_host = mail_env["SMTP_HOST"]
    smtp_port = int(mail_env["SMTP_PORT"])

    context = ssl.create_default_context()
    with smtplib.SMTP(smtp_host, smtp_port, timeout=60) as server:
        server.ehlo()
        server.starttls(context=context)
        server.ehlo()
        server.login(mail_env["SMTP_USER"], mail_env["SMTP_PASS"])
        server.send_message(msg)


def main() -> int:
    args = parse_args()

    students_root = Path(args.students_root).resolve()
    work_dir = Path(args.work_dir).resolve()

    try:
        student_dirs = get_student_dirs(students_root)
        archive_path = build_archive(student_dirs, students_root, work_dir)
        cleanup_old_archives(work_dir, args.keep_days)
        send_mail(archive_path, args.to, args.subject_prefix)
    except Exception as exc:  # noqa: BLE001
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(f"Archive sent successfully: {archive_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
